# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-latest
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          cache: 'npm'
          node-version: 22
      - run: npm ci --ignore-scripts --no-audit --no-fund
      - run: npm test
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  check:
    name: Check types
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          cache: 'npm'
          node-version: 22
      - run: npm ci --ignore-scripts --no-audit --no-fund
      - run: npm run check  --if-present

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          cache: 'npm'
          node-version: 22
      - run: npm ci --ignore-scripts --no-audit --no-fund
      - run: npm run build

  lint-code:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          cache: 'npm'
          node-version: 22
      - run: npm ci --ignore-scripts --no-audit --no-fund
      - run: npm run build
      - run: npm run lint

  lint-pkg:
    name: Lint package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          cache: 'npm'
          node-version: 22
      - run: npm ci --ignore-scripts --no-audit --no-fund
      - run: npm run build
      - run: npm run lint-package

  npm-audit:
    name: Audit packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          cache: 'npm'
          node-version: 22
      - run: npm audit --audit-level=high
